/// The error module, which contains information about different errors and also handles them.
pub mod error;

/// The stack module, which contains the stack and different functions to control the stack.
pub mod stack;

/// The token module, which contains the different tokens and the token kinds. These are generated by the lexer.
pub mod token;

/// The frames module, which contains the frame struct. Frames are used when the VM jumps to a label.
pub mod frames;